# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('report_stat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('car_loc', models.CharField(max_length=100)),
                ('rep_person', models.FileField(upload_to=b'')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsys.Car')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('mid_name', models.CharField(max_length=100)),
                ('license_id', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsys.User'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsys.User'),
        ),
    ]
