# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsys', '0002_auto_20170805_0730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
