# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsys', '0005_auto_20170810_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='report_stat',
            new_name='car_stat',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='ignition_stat',
            new_name='report_stat',
        ),
    ]
