# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsys', '0006_auto_20170810_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='car_ignition',
            field=models.BooleanField(default=False),
        ),
    ]
