# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsys', '0007_report_car_ignition'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='car_loc_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='car_photo_stat',
            field=models.BooleanField(default=False),
        ),
    ]
