# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsys', '0009_auto_20170811_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='car_loc_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='car_photo_date',
        ),
    ]
