# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsys', '0010_auto_20170811_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_reported',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
